### ISSUE TITLE
Fix JS in ROI.js (issue w/ inputs)

### ISSUE THREAD

**Issue by wardsandler** [320NY-Websites/d2g#1]
Hey Gil, left you a note on line 176 of roi.js.

Right now the code you wrote is affecting every input throughout the site (including the contact forms i just pushed). I need you to modify it so it only affects inputs on the ROI page

**Comment by gcohen55** [comment]
hey ward,

i threw something in there that looks at the window.location.href and bails out before attaching to change events.

ideally, roi.js wouldn't be called on any other page /but/ the roi page, but this work around should work just fine.

**Comment by wardsandler** [comment]
Ok now the script only loads on the ROI page
